#!/bin/sh

# in purple
log() {
  printf "\033[35m %s \033[0m\n" "$1"
}

log "pre-push: checking types..."
./node_modules/.bin/tsc --noEmit || { log "pre-push: type checking failed, aborting push"; exit 1; }

log "pre-push: running tests..."
npm test || { log "pre-push: tests failed, aborting push"; exit 1; }
